[package]
name = "dashboard-api"
version = "0.1.11"
edition = "2024"
repository = "https://github.com/juravenator/lcars-dashboard"

[dependencies]
axum = "0.8.8"
serde_json = "1.0.149"
tokio = { version = "1.50.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.102"
tower-http = { version = "0.6.6", features = ["cors"] }
rust-embed = { version = "8.5.0", features = ["interpolate-folder-path", "compression"] }
mime_guess = "2.0.5"
kube = { version = "3.0.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.27.0", features = ["v1_31", "schemars"] }
reqwest = "0.13.2"
rustls = "0.23.37"

[profile.release]
strip = true
opt-level = "z"
lto = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
